import requests
import pandas as pd

SYMBOLS = {
    "SPY": "S&P",
    "QQQ": "Nasdaq",
    "DIA": "Dow",
    "EUR": "Euro",
    "GBP": "British Pound",
    "JPY": "Japanese Yen",
    "CNY": "Chinese Yuan",
    "USD": "Dollar",
    "BTC": "Bitcoin",
    "QQQ": "Tech",
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "GOOGL": "Alphabet|Google",
    "GOOG": "Alphabet|Google",
    "AMZN": "Amazon",
    "NVDA": "NVIDIA",
    "META": "Meta",
    "BRK.B": "Berkshire Hathaway",
    "TSLA": "Tesla",
    "UNH": "UnitedHealth",
    "LLY": "Eli Lilly",
    "V": "Visa",
    "JPM": "JPMorgan",
    "XOM": "Exxon Mobil",
    "MA": "Mastercard",
    "AVGO": "Broadcom",
    "JNJ": "Johnson & Johnson",
    "PG": "Procter & Gamble",
    "HD": "Home Depot",
    "MRK": "Merck",
    "CVX": "Chevron",
    "ABBV": "AbbVie",
    "COST": "Costco",
    "PEP": "PepsiCo",
    "ADBE": "Adobe",
    "WMT": "Walmart",
    "CRM": "Salesforce",
    "KO": "Coca-Cola",
    "MCD": "McDonald's",
    "BAC": "Bank of America",
    "ACN": "Accenture",
    "TMO": "Thermo Fisher",
    "ABT": "Abbott",
    "DIS": "Disney",
    "DHR": "Danaher",
    "LIN": "Linde",
    "WFC": "Wells Fargo",
    "NFLX": "Netflix",
    "TXN": "Texas Instruments",
    "VZ": "Verizon",
    "NEE": "NextEra Energy",
    "PM": "Philip Morris",
    "ORCL": "Oracle",
    "AMGN": "Amgen",
    "INTC": "Intel",
    "MS": "Morgan Stanley",
    "HON": "Honeywell",
    "UNP": "Union Pacific",
    "IBM": "IBM",
    "QCOM": "Qualcomm",
    "LOW": "Lowe's",
    "SBUX": "Starbucks",
    "MDT": "Medtronic",
    "GE": "General Electric",
    "ELV": "Elevance Health",
    "RTX": "RTX|Raytheon",
    "GS": "Goldman Sachs",
    "ISRG": "Intuitive Surgical",
    "BLK": "BlackRock",
    "PLD": "Prologis",
    "AMT": "American Tower",
    "CVS": "CVS Health",
    "SYK": "Stryker",
    "SCHW": "Charles Schwab",
    "SPGI": "S&P Global",
    "CAT": "Caterpillar",
    "MDLZ": "Mondelez",
    "LRCX": "Lam Research",
    "ADI": "Analog Devices",
    "MMC": "Marsh McLennan",
    "MO": "Altria",
    "GILD": "Gilead",
    "ZTS": "Zoetis",
    "DE": "Deere",
    "C": "Citigroup",
    "ADP": "ADP|Automatic Data Processing",
    "CB": "Chubb",
    "CI": "Cigna",
    "MU": "Micron",
    "REGN": "Regeneron",
    "VERX": "Vertex",
    "USB": "US Bank|U.S. Bancorp",
    "PGR": "Progressive",
    "DUK": "Duke Energy",
    "SHW": "Sherwin-Williams",
    "CSCO": "Cisco",
    "SLB": "Schlumberger",
    "PNC": "PNC",
    "GM": "General Motors",
    "ITW": "Illinois Tool Works",
    "TFC": "Truist",
    "AON": "Aon",
    "BDX": "Becton Dickinson",
    "FDX": "FedEx",
    "CL": "Colgate-Palmolive",
    "APD": "Air Products",
    "BSX": "Boston Scientific",
    "EOG": "EOG Resources",
    "MPC": "Marathon Petroleum",
    "D": "Dominion Energy",
    "WM": "Waste Management",
    "GD": "General Dynamics",
    "HUM": "Humana",
    "FIS": "Fidelity National Information Services",
    "AIG": "American International Group",
    "CRWD": "CrowdStrike",
    "ET": "Energy Transfer",
    "INTU": "Intuit",
    "AVAV": "AeroVironment",
    "CHWY": "Chewy",
    "DG": "Dollar General",
    "LULU": "Lululemon",
    "AMD": "Advanced Micro Devices",
    "RH": "RH",
    "BA": "Boeing",
    "NKE": "Nike",
    "SPOT": "Spotify",
    "LEGO": "Lego",
    "JHX": "James Hardie",
    "KTOS": "Kratos Defense",
    "GIS": "General Mills",
    "DOCU": "DocuSign",
    "STZ": "Constellation Brands",
    "TXT": "Textron",
    "LMT": "Lockheed Martin",
    "NOC": "Northrop Grumman",
    "CAD": "Cadre Holdings",
    "SARO": "StandardAero",
    "EVTL": "Vertical Aerospace",
    "SHEL": "Shell",
    "GSK": "GSK",
    "UL": "Unilever",
    "TT": "Trane Technologies",
    "SAN": "Banco Santander",
    "NVS": "Novartis",
    "RIVN": "Rivian",
    "RDDT": "Reddit",
    "BABA": "Alibaba",
    "CHPT": "ChargePoint",
    "DELL": "Dell",
    "APP": "AppLovin",
    "PANW": "Palo Alto Networks"
}

def article_mentions_symbol_or_company(title):
    title_lower = title.lower()
    for symbol, company in SYMBOLS.items():
        if symbol.lower() in title_lower:
            return True
        for name in company.split('|'):
            if name.lower() in title_lower:
                return True
    return False
